### PR TITLE
Add Helm chart

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by treydock** [comment]
The Helm chart version mirrors the application version, so have to update `Chart.yaml` versions when application has new version.  Another way people manage Helm charts is make chart version be separate from application and only published on like `helm-chart-X.Y.Z` type tags.

Also I think there is step needed to setup `gh-pages` branch: https://jiafulow.github.io/blog/2020/07/09/create-gh-pages-branch-in-existing-repo/.  I don't think the GH Action for publishing the chart will handle that initial branch creation.

**Comment by clementnuss** [comment]
Thanks for your work! seems good, I will create the `gh-pages` branch. I will also edit my pipeline so it doesn't try to run publish on forks (the secret isn't sent for security reasons so it fails).

There seems to be an issue during chart testing though: https://github.com/postfinance/kubelet-csr-approver/runs/4364299845?check_suite_focus=true#step:13:212
An idea why this happens?

**Comment by clementnuss** [comment]
branch created. regarding the Helm Chart version, we can go for the mirror app version solution.
Couldn't it be possible to get that info from the tag? with something such as what I did here: https://github.com/postfinance/kubelet-csr-approver/blob/main/.github/workflows/publish.yaml#L76

**Comment by treydock** [comment]
>  regarding the Helm Chart version, we can go for the mirror app version solution. Couldn't it be possible to get that info from the tag? 

I think only way to do that would be to modify the `Chart.yaml` during the Github Action before the chart is published. The issue I see with that is the version published would not match the version in git, which might confuse people.  Could potentially replace the value with like `@TAG@` so clearly the value isn't set so maybe clear it's dynamically replaced.  So have like this:

```yaml
version: @TAG@
appVersion: @TAG@
```

Then in GH Action do this:

```bash
sed -i "s|@TAG@|$TAG|g" deploy/charts/kubelet-csr-approver/Chart.yaml
```

If that seems like something you'd like to have done, I can make that adjustment

**Comment by treydock** [comment]
> 
> There seems to be an issue during chart testing though: https://github.com/postfinance/kubelet-csr-approver/runs/4364299845?check_suite_focus=true#step:13:212 An idea why this happens?

I think I fixed this. May have forgot to pass flags to `wget` to make it not have errors.

**Comment by clementnuss** [comment]
> > There seems to be an issue during chart testing though: https://github.com/postfinance/kubelet-csr-approver/runs/4364299845?check_suite_focus=true#step:13:212 An idea why this happens?
> 
> I think I fixed this. May have forgot to pass flags to `wget` to make it not have errors.

strange, on one occasion earlier today it worked, and now with your update it still doesn't. might it be that the busybox container tries to early to connect to the metrics endpoint? adding a few seconds of delay could help?

**Comment by clementnuss** [comment]
> > regarding the Helm Chart version, we can go for the mirror app version solution. Couldn't it be possible to get that info from the tag?
> 
> I think only way to do that would be to modify the `Chart.yaml` during the Github Action before the chart is published. The issue I see with that is the version published would not match the version in git, which might confuse people. Could potentially replace the value with like `@TAG@` so clearly the value isn't set so maybe clear it's dynamically replaced. So have like this:
> 
> ```yaml
> version: @TAG@
> appVersion: @TAG@
> ```
> 
> Then in GH Action do this:
> 
> ```shell
> sed -i "s|@TAG@|$TAG|g" deploy/charts/kubelet-csr-approver/Chart.yaml
> ```
> 
> If that seems like something you'd like to have done, I can make that adjustment

Didn't think about it that way. let's try to have it as simple as possible. I don't expect a tremendous number of updates, I think we can manually change the Chart.yaml version when releasing it :)

**Comment by treydock** [comment]
Strange, my forked PR is passing: https://github.com/treydock/kubelet-csr-approver/actions/runs/1522769301

The error indicates the DNS name for the metric service isn't resolving.  Based on the log timestamps the metric service for kubelet-csr-approver started 2 seconds before wget was run.  It could be the Kubernetes service DNS was delayed. I added a sleep to see if that solves the issue.

**Comment by clementnuss** [comment]
It seems it has worked! it's getting late here in Switzerland, I'll review that once more tomorrow and merge the PR!
Thanks for your work 👏🏻

**Review by clementnuss — APPROVED** [review]

**Pull request merged**
